# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Session Settings
# Auto Save Session
c.auto_save.session = True
# Only restore the tab if opened
c.session.lazy_restore = True

# new tabs (middleclick/ctrl+click) in the background
c.tabs.background = True
# select previous tab instead of next tab when deleting current tab
c.tabs.select_on_remove = 'prev'
# open unrelated tabs after the current tab not last
c.tabs.new_position.unrelated = 'next'
c.tabs.min_width = 200
c.tabs.title.format = '{index}{private}{title_sep}{title}'

c.aliases['h'] = 'help'
c.aliases['r'] = 'config-source'
c.aliases['o'] = 'open'

c.fonts.monospace = 'Roboto'
c.scrolling.bar = "always"
c.scrolling.smooth = True

# Set my github page as my start page
c.url.start_pages = "https://github.com/adithyabhatkajake"
c.url.default_page = 'https://github.com/adithyabhatkajake'
c.url.searchengines['aw'] = "https://wiki.archlinux.org/?search={}"
c.url.searchengines['g'] = "https://www.google.com/search?hl=en&q={}"
c.url.searchengines['am'] = "http://www.amazon.com/s/url=search-alias%3Daps&field-keywords={}"
c.url.searchengines['git'] = "http://github.com/search?q={}"
c.url.searchengines['wiki'] = "https://en.wikipedia.org/w/index.php?search={}"
c.url.searchengines['r'] = "http://www.reddit.com/r/{}/"
c.url.searchengines['yt'] = "http://www.youtube.com/results?search_query={}"
c.url.searchengines['sc'] = "https://soundcloud.com/search?q={}"
c.url.searchengines['sp'] = "https://open.spotify.com/search/results/{}"
c.url.searchengines['gs'] = "https://scholar.google.com/scholar?hl=en&q={}"

# To enable players
c.content.plugins = True

# To support DRM enabled content like Netflix, Spotify, etc
c.qt.args = ["ppapi-widevine-path=/usr/lib/qt/plugins/ppapi/libwidevinecdmadapter.so"]

# Set up bindings
# Git clone binding
config.bind(";c", "spawn --userscript ~/dotfiles/gitCloner.sh", "caret")

# Download Bindings
config.bind(";gd", "set downloads.location.directory ~/Documents ;; hint links download")
config.bind(";gp", "set downloads.location.directory ~/Pictures ;; hint links download")
config.bind(";gb", "set downloads.location.directory /run/media/haxolotl/Backup ;; hint links download")
config.bind(";gm", "set downloads.location.directory /run/media/haxolotl/Media ;; hint links download")
config.bind(";gl", "set downloads.location.directory /run/media/haxolotl/Backup/Literature ;; hint links download")
config.bind(";gn", "set downloads.location.directory /run/media/haxolotl/Backup/Notes ;; hint links download")
config.bind(";gM", "set downloads.location.directory /run/media/haxolotl/Media/Movies ;; hint links download")
config.bind(";gT", "set downloads.location.directory /tmp/ ;; hint links download")
config.bind(";gt", "set downloads.location.directory /run/media/haxolotl/Media/TV Series ;; hint links download")

# Fix h to go to left tab; l to go to right tab
# config.unbind("H",mode="normal")
# config.unbind("L",mode="normal")
# config.bind("H","tab-prev",mode="normal")
# config.bind("L","tab-next",mode="normal")
# config.bind("Alt+h","back",mode="normal")
# config.bind("Alt+l","forward",mode="normal")



# Todo:
# Download all PDFs in a page
